### ISSUE TITLE
Question about K means number of cluster?

### ISSUE THREAD

**Issue by FromA2Z** [HugoZHL/MEVI#1]
Hello, thank you very much for this work, it's fantastic.
There is one problem I would like to ask you.
At the time of reproduction, when the document is subjected to multiple levels of K Means clustering, the final number of clusters ranges from 5K-20W (the ckpt you provided can cluster up to 70W or more) .
The K means clustering results seem to be very unstable（number of culster）, what do you think is the reason?

**Comment by HugoZHL** [comment]
Thank you for your interest in our work!
In K-Means clustering, since we need to set "K" in each clustering process, the number of clusters should be controllable.
So I think maybe the instability you mentioned here is about "the number of documents in each cluster"?
Since K-Means clustering only considers the distance, without including a constraint on the number of documents (for balance), it is normal for such phenomenon to happen.
In our implementation, we use Residual Quantization, which clusters all the documents in every level, and currently we have not focused on this problem.
If you would like to address the problem, there are some existing solutions on balanced-kmeans, which may further improve our work.

**Comment by FromA2Z** [comment]
Thank you for your reply. I found that in this repository, K-means uses the classic Euclidean distance, while T5 and its variants use cosine distance (dot product). So, during K-means, I normalized the encoding, which stabilized clustering to over 700,000.
